### ISSUE TITLE
[enhancement] add horizontal view support

### ISSUE THREAD

**Issue by Mravuri96** [mafanwei/WheelChooser#1]
Would like to see a horizontal wheel, other that that great plugin.

**Comment by mafanwei** [comment]
good idea，I will make it. Anyone wants help?

**Comment by Mravuri96** [comment]
> good idea，I will make it. Anyone wants help?



I actually got it to work, not sure if its efficient but, here ya go [https://gist.github.com/Mravuri96/1716c1679cff359cc93f8b3735346325](url)

Demo:
 ![horizontal scroll demo](https://media.giphy.com/media/hWAXftK0kSm3JbGdXt/giphy.gif)

**Comment by mafanwei** [comment]
I read your code,I think that's ok.

I read the source code of ListView. In the Viewport of the ScrollView, I found the answer to why the ListView can set the direction.

I also read the source code of ListWheelScrollView. I noticed that if we wanted to implement the same functionality, we had to update the RenderListWheelViewport, which doesn't seem like a good idea.

Thank you for your thoughts.

**Comment by mafanwei** [comment]
I have updated the plugin and already support the horizontal list.
