### ISSUE TITLE
unSelectTextStyle for custom

### ISSUE THREAD

**Issue by artvation** [mafanwei/WheelChooser#10]
Hey,

is there an option to set
unSelectTextStyle and selectTextStyle for custom Wheels too?

Unfortunately it is just available for the two others at the moment. 

best regards,
Anni

**Comment by albus25** [comment]
Any update?

**Comment by mafanwei** [comment]
Because costom is an unknown child, so there is no style.

You can obtain the child location according to onValueChanged, and then modify the style by yourself.

You can take a look at this: wheel_chooser.dart  function _buildListItems.

**Comment by albus25** [comment]
It works, thanks.
