### ISSUE TITLE
Error: Final field 'physics' is not initialized by this constructor.

### ISSUE THREAD

**Issue by barbrady91** [mafanwei/WheelChooser#14]
Hey, I get the following error if I try to run my app:

```
Failed to build iOS app
Error (Xcode): ../../.pub-cache/hosted/pub.dev/wheel_chooser-1.1.0/lib/wheel_chooser.dart:53:3: Error: Final field 'physics' is not initialized by this constructor.

Could not build the application for the simulator.
Error launching application on iPhone 14.
```

Dart Analysis does not show any issues.

The error occurred after I updated Xcode to version 14.3 and Flutter to the latest stable version 3.7.9.
Not 100% sure which of these two updates caused the problem.

I tried to update wheel chooser to the latest version 1.1.0 but unfortunately that did not solved the issue.

Any idea what is going wrong here?

I would really appreciate any help.

Greetings Marc

**Comment by mafanwei** [comment]
Try the lastest

**Comment by barbrady91** [comment]
Thank you very much for your super fast answer.
I tested the latest version but I get now a different error:

`Error (Xcode): ../../.pub-cache/hosted/pub.dev/wheel_chooser-1.1.1/lib/wheel_chooser.dart:130:3: Error: Final field 'choices' is not initialized by this constructor.`

**Comment by mafanwei** [comment]
Try this:
wheel_chooser:
    git:
      url: https://github.com/mafanwei/WheelChooser

**Comment by barbrady91** [comment]
Now I get the following error:

`Error (Xcode): ../../.pub-cache/git/WheelChooser-ea32daaa66db9dafeec104dad38e41cd7027b286/lib/wheel_chooser.dart:130:3: Error: Final field 'onChoiceChanged' is not initialized by this constructor.`

**Comment by mafanwei** [comment]
Try again?
I don't have a computer at hand, I use GiTub to edit.

**Comment by barbrady91** [comment]
Now everything works.
Thank you very much.
