### ISSUE TITLE
Can we select by clicking instead of scrolling?

### ISSUE THREAD

**Issue by fremfi** [mafanwei/WheelChooser#6]
It seems alot of user try to click instead of scrolling, is there a way to accommodate selection by clicking?
Some how the tap events on the children items aren't registering. I think it's because it's being absorbed by the slider events?

**Comment by Venusdjinni** [comment]
I have the same problem here, I can't handle the tap events on children. Any solution?

**Comment by fremfi** [comment]
> I have the same problem here, I can't handle the tap events on children. Any solution?

I ended up switching to this package: https://pub.dev/packages/carousel_slider
hope that helps

**Comment by Venusdjinni** [comment]
Just tried it and it does exactly what I wanted. Thank you
